### ISSUE TITLE
CF standard name table is outdated

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/py-thesaurus-interface#35]
We're using version 30, whereas the latest one is number 76 (https://cfconventions.org/Data/cf-standard-names/current/build/cf-standard-name-table.html). 

- [x] Change to using the Marine Metadata Interoperability Ontology Registry and Repository (https://mmisw.org/ont/cf/parameter) - that should always have the latest version

- [x] We should note the CF version number and origin (as a uri) in the local copy - see how it is done in `gcmd_vocabulary.py`

**Comment by akorosov** [comment]
Closed in #36 by @mortenwh
