### ISSUE TITLE
GCMD keywords versions are not pinned

### ISSUE THREAD

**Issue by aperrin66** [nansencenter/py-thesaurus-interface#41]
Every time vocabularies are updated locally, the latest version from GCMD keywords is pulled.

This might be undesirable, especially when there are updates to existing keywords (it was the case recently for Sentinel-1: "SENTINEL-1A" became "Sentinel-1A" and the same for 1B).
This requires updating existing django-geo-spaas databases, for example.

It would be worthwhile to explore a bit the [GCMD API](https://gcmd.earthdata.nasa.gov/kms/) and see if the version of keywords can be pinned in [pythesintrc.yaml](https://github.com/nansencenter/py-thesaurus-interface/blob/master/pythesint/pythesintrc.yaml).
That way, fixed keyword versions would be associated with a pythesint release, increasing the reliability of the package.

**Comment by mortenwh** [comment]
I think we also use only the latest version of the CF vocabulary now. Would it be possible to choose the version numbers based on what's currently in the database? I'm afraid that fixing the versions in `pythesintrc.yaml` would be problematic..

**Comment by aperrin66** [comment]
@mortenwh I am not sure I understand what you have in mind. Do you mean using the "Revision" information stored in some of the json files?
What would be wrong with pinning the versions in `pythesintrc.yaml`? If it is not flexible enough, maybe we can allow an alternative location for the pythesintrc file (like `~/.pythesintrc.yaml`), so that users can specify their own versions if needed?

**Comment by mortenwh** [comment]
By "see if the version of keywords can be pinned in pythesintrc.yaml" I understood that you wanted to specify in `pythesintrc.yaml` which version of the vocabularies should be used in pythesint. I think it is a good idea, and maybe even mandatory, to have version information for the various vocabularies but it should be stored in the json files, not fixed/hardcoded in `pythesintrc.yaml`. In addition, we should implement functionality that lets the user specify the versions of the vocabularies to use.

**Comment by aperrin66** [comment]
@mortenwh this is done in #48
