### ISSUE TITLE
Running update_all_vocabularies() on package install can be problematic

### ISSUE THREAD

**Issue by aperrin66** [nansencenter/py-thesaurus-interface#55]
Right now, `update_all_vocabularies()` is run every time the package is installed.
If something goes wrong during the execution, the installation of the package fails.

This kind of failure is often caused by a change on the source of one of the vocabularies, which can be solved quite easily by changing the version of the source that is used. But if the installation fails, it is impossible to try that.

There would be several solutions to fix that:
- catching exceptions in the installation script to avoid failing (not a good solution in my opinion)
- make it possible to disable the update on install (using env var or CLI argument)
- call `update_all_vocabularies()` on import instead of on install (only if there are no local files present, to avoid calling it every time)

What do you think @akorosov?

**Comment by akorosov** [comment]
It doesn't run update_all_vocabularies() when I install it now. Maybe it is better to just remove this functionality completely. And let the user run it manually (or add explicitly to Dockerfile)
