### ISSUE TITLE
https://gcmdservices.gsfc.nasa.gov/ is not accessible (retired)

### ISSUE THREAD

**Issue by an-ivanov** [nansencenter/py-thesaurus-interface#65]
The gcmdservices.gsfc.nasa.gov server is not accessible (retired) and has to be replaced with https://gcmd.earthdata.nasa.gov.
https://forum.earthdata.nasa.gov/viewtopic.php?p=10734

**Comment by chhorvat** [comment]
Just want to reiterate this - a huge problem for any codes that rely on pythesint. Is there a planned workaround?
