### ISSUE TITLE
CF specific code should not be in Vocabulary.find_keyword

### ISSUE THREAD

**Issue by aleksandervines** [nansencenter/py-thesaurus-interface#7]
Regarding this code:

```
        # OBS: This works for the gcmd keywords but makes no sense for the cf
        # standard names - therefore always search the cf standard names by
        # standard_name only..
        for m in matches:
            remaining = {}
            for i in ii:
                remaining[keys[i]] = m[keys[i]]
            if not any(val for val in remaining.itervalues()):
                return m
```

cf_vocabulary should rather override the find_keyword method, or the find_keyword method should be made more generic and then overriden.

I vote for generic and overriden, consider the following scenario:
What if there are multiple matches? e.g. I search for "Imaging Radars"? Then it should return all matches (currently it returns nothing, which I think is a bug).

Now, if it would return a list of all matches, then cf_vocabulary could override this, by calling the find_keyword from superclass, and then perform the search only on standard_name only.

BUT - why are we only searching standard names? I think there should be an option here. Perhaps I don't know what standard name to use, and want to search in the description also?

**Comment by aleksandervines** [comment]
As the "new interface" will not provide the find_keyword method to users, but let the user rely on e,g, get_gcmd_platform, I don't think it is as important to be able to return all found values - for meg, get_ implies more that you will get one result than find_.. 

However, I then suggest to extend the api with search_ methods, e.g. 
```
search_gcmd_instrument("Imaging Radars")
search_gcmd_instrument("*Radars")
search_gcmd_instrument("*Radars","Type")
```
etc

**Comment by aleksandervines** [comment]
I still can't make sense of ii and matching_key, as matching_key will always just be the value of the last matching_key found.

@mortenwh - You wrote this?

**Comment by mortenwh** [comment]
Example:
```
import pythesint
a = pythesint.get_gcmd_location('africa')
```
From debugging:
```
ipdb> p matching_key
u'Location_Type'
ipdb> p d.keys()
[u'Location_Category', u'Location_Subregion1', u'Location_Type', u'Location_Subregion3', u'Location_Subregion2']
```

When I coded this, I assumed that the matching key was unique, i.e., that if Africa is found under ```'Location_Type'``` it can't be in ```'Location_Subregion1'```, etc. But maybe this is not the case...

BUT: ```get_list``` should return an ordered dictionary, so the (GCMD) keys will be ordered from general to specific. By storing the matching key, we can make sure that the most general dictionary is returned, i.e., by ensuring that ```'Location_Subregion1'```, ```'Location_Subregion2'```, and ```'Location_Subregion3'```are empty. But it seems the ```JSONVocabulary.get_list``` doesn't return ordered dictionaries, so then this shouldn't work as expected althoug it still does..

**Comment by mortenwh** [comment]
Ok - it doesn't fail because the most general dictionary containing ```africa``` is the first list item... This will be the general case for the gcmd keywords, and then it could be enough to return the first match, although I think I prefer a proper check..

**Comment by mortenwh** [comment]
Is this issue now solved if we add the ```search_*``` methods to return all matches?

**Comment by akorosov** [comment]
Yes, I believe

**Comment by aleksandervines** [comment]
There still is a bug in here, I will fix it, and add tests which tests this case when I got the time. 

`best_match_empty_cells is always 0.`
